
package view;

import java.sql.*;
import java.util.*;
import javax.swing.JFrame;
import java.security.*;
import javax.swing.JOptionPane;


public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    private String db_url="jdbc:mysql://localhost:3306/registration";
    private String db_username="root";
    private String db_passwd="";
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);  // center form in the screen
        this.setSize(418,525);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        stdID = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        fac = new javax.swing.JLabel();
        dpt = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jButton_Register_ = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        PASS = new javax.swing.JPasswordField();
        studentID = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        faculty = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(196, 69, 115));

        jLabel1.setBackground(new java.awt.Color(196, 96, 115));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");

        jLabelClose.setBackground(new java.awt.Color(196, 96, 115));
        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setBackground(new java.awt.Color(196, 96, 115));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMin))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 50);

        jPanel2.setBackground(new java.awt.Color(89, 98, 117));

        stdID.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        stdID.setText("StudentID:");

        fname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fname.setText("FirstName:");

        lname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lname.setText("LastName:");

        fac.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fac.setText("Faculty:");

        dpt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        dpt.setText("Department:");

        pass.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        pass.setText("Password:");

        jButton_Register_.setBackground(new java.awt.Color(30, 144, 255));
        jButton_Register_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Register_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register_.setText("Register");
        jButton_Register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Register_MouseClicked(evt);
            }
        });
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });

        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("click here to Login");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        PASS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        studentID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        firstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        faculty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton_Delete.setBackground(new java.awt.Color(0, 98, 102));
        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete.setText("Delete");
        jButton_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DeleteMouseClicked(evt);
            }
        });
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Update.setBackground(new java.awt.Color(163, 203, 56));
        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Update.setText("Update");
        jButton_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_UpdateMouseClicked(evt);
            }
        });
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stdID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fname)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(dpt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lname, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabelLogin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton_Register_)))
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Update)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdID)
                    .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fac)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpt)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Register_, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabelLogin)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 400, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed
    if(studentID.getText().isEmpty() || firstname.getText().isEmpty() || lastname.getText().isEmpty() ||faculty.getText().isEmpty() || department.getText().isEmpty() ||PASS.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter All Your Details","Data required",JOptionPane.WARNING_MESSAGE);
        }
        else if(PASS.getText().length() >= 8 && PASS.getText().length() <=16 && studentID.getText().length()==5) {
            try {
                // create connection
                Connection con = DriverManager.getConnection(db_url,db_username,db_passwd);
                
                //? create statement
                    PreparedStatement st = con.prepareStatement("insert into app_users values(?,?,?,?,?,?)");
                    st.setString(1, studentID.getText());
                    st.setString(2, firstname.getText());
                    st.setString(3, lastname.getText());
                    st.setString(4, faculty.getText());
                    st.setString(5, department.getText());
                    
                    st.setString(6, PASS.getText());
                    // execute statemet
                    int rowAffected = st.executeUpdate();
                    // close connection
                    con.close();
                    if(rowAffected>=1){
                        JOptionPane.showMessageDialog(this, "Data Saved Successful");
                    }else{
                        JOptionPane.showMessageDialog(this, "Data Not Saved Successful");
                    }
                    studentID.setText("");
                    firstname.setText("");
                    lastname.setText("");
                    faculty.setText("");
                    department.setText("");
                    PASS.setText("");
            } catch (Exception ex) {
                ex.printStackTrace();
            } 
        } 
        else if (studentID.getText().length()!=5){
            JOptionPane.showMessageDialog(this, "Your ID msut have 5 characters");
        }
        else {
             if(PASS.getText().length()<8)
             {
                 JOptionPane.showMessageDialog(this, "Password too short, must at least  be of 8  characters");
             }
             else if(PASS.getText().length()>16)
             {
                 JOptionPane.showMessageDialog(this, "Password too long, must at most be of 16 characters");
             }
        }
    }//GEN-LAST:event_jButton_Register_ActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lgf.setSize(418,330);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButton_Register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Register_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Register_MouseClicked

    private void jButton_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteMouseClicked

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        try{
            //create a connection
            Connection con = DriverManager.getConnection(db_url,db_username,db_passwd);
            //create statement
            PreparedStatement pst = con.prepareStatement("delete from app_users where Stud_ID=?");
            pst.setString(1, studentID.getText());
            //execute statement
            int rowAffected = pst.executeUpdate();
            //close connection
            con.close();
            if(rowAffected >=1){
                JOptionPane.showMessageDialog(null, "Data Deleted Successful");
            }else{
                JOptionPane.showMessageDialog(null, "Data NOT Deleted Successful");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_UpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_UpdateMouseClicked

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        try {
    // create a connection
    Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
    // create statement
    PreparedStatement st = con.prepareStatement("update app_users set fname=?,lname=?, Faculty=?, department=?, password=? where Stud_ID=?");
    st.setString(1, firstname.getText());
    st.setString(2, lastname.getText());
    st.setString(3, faculty.getText());
    st.setString(4, department.getText());
    st.setString(5, PASS.getText());
    st.setString(6, studentID.getText());
    // execute statement
    int rowAffected = st.executeUpdate();
    // close statement and connection
    st.close();
    con.close();
    if (rowAffected >= 1) {
        JOptionPane.showMessageDialog(this, "Data updated Successful");
    } else {
        JOptionPane.showMessageDialog(this, "Data Not updated Successful");
    }
} catch (Exception ex) {
  ex.printStackTrace();
    
}

    }//GEN-LAST:event_jButton_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PASS;
    private javax.swing.JTextField department;
    private javax.swing.JLabel dpt;
    private javax.swing.JLabel fac;
    private javax.swing.JTextField faculty;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel fname;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Register_;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel stdID;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
